[workspace]
members = ["mini-lsm", "xtask"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
homepage = "https://github.com/buraksenn/mini-lsm"
license = "Apache-2.0"
repository = "https://github.com/buraksenn/mini-lsm"

[workspace.dependencies]
anyhow = "1"
bytes = "1"
